'use strict';

/**
* @ngdoc service
* @name clientApp.entries
* @description
* # entries
* Factory in the clientApp.
*/
angular.module('clientApp')
.factory('entries', function ($q, $window) {
    var vm = this;
    vm.database = $window.firebase.database();

    function getUserEntries(uid) {
        return $window.firebase.database().ref('/users/' + uid + '/entries').once('value');
    }

    function createEntry(entry, uid) {
        // Generate a reference to a new location and add some data using push()
        var newEntryRef = $window.firebase.database().ref('entries');
        var newEntryPush = newEntryRef.push();
        newEntryPush.set({
            'title': entry.title,
            'message': entry.message,
            'created_at': (new Date()).getTime(),
            'created_by': uid
        });
        // Get the unique ID generated by push() by accessing its key
        var EntryId = newEntryPush.key;
        return updateUserEntries(EntryId, uid, entry);
    }

    function updateUserEntries(entryId, uid, entry) {
        var entryRef = $window.firebase.database().ref('users/' + uid + '/entries');
        return entryRef.child(entryId).set({
            'title': entry.title,
            'message': entry.message,
            'created_at': (new Date()).getTime(),
            'created_by': uid
        });
    }

    return {
        getUserEntries: getUserEntries,
        createEntry: createEntry
    };
});
